CREATE DATABASE Family

CREATE TABLE Tb_Users(

	uid INT(4) NOT NULL PRIMARY KEY COMMENT'成员编号',
	uname VARCHAR(20) NOT NULL COMMENT'姓名',
	upart VARCHAR(20) NOT NULL COMMENT'家庭角色',
	ubirth DATETIME NOT NULL COMMENT'出生日期',
	upassword VARCHAR(20) NOT NULL COMMENT'密码',
	ucompany VARCHAR(30) COMMENT'工作单位',
	uremark VARCHAR(100) COMMENT'备注'
	
)COMMENT'家庭成员表' CHARSET='utf8';

CREATE TABLE Tb_InOutField(

	xid INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT'编号',
	xName VARCHAR(20) NOT NULL COMMENT'项目名',
	xtype VARCHAR(20) NOT NULL COMMENT'收支类型'
	
)COMMENT'收支项目表' CHARSET='utf8';

CREATE TABLE tb_InOutInfo(

	rid INT(4) NOT NULL PRIMARY KEY COMMENT'编号',
	uid INT(4) NOT NULL COMMENT'操作人',
	xid INT(4) NOT NULL COMMENT'收支项目',
	rmoney FLOAT(8) NOT NULL COMMENT'金额',
	rdate DATETIME NOT NULL COMMENT'操作时间',
	rmenu VARCHAR(100) COMMENT'备注',
	
	CONSTRAINT FOREIGN KEY (uid)
	REFERENCES Tb_Users(uid),
	
	CONSTRAINT FOREIGN KEY (xid)
	REFERENCES Tb_InOutField(xid)
	
)COMMENT'日常收支表' CHARSET='utf8';

