CREATE TABLE bbsUsers(
	uid INT AUTO_INCREMENT PRIMARY KEY NOT NULL COMMENT'用户编号',
	uname VARCHAR(20) NOT NULL COMMENT'用户名',
	upassword VARCHAR(20) NOT NULL COMMENT'用户密码',
	uemail VARCHAR(50) COMMENT'电子邮箱',
	usex VARCHAR(6) COMMENT'性别',
	uregdate TIMESTAMP DEFAULT NOW() COMMENT'注册时间'
)

CREATE TABLE bbsTopics(
	tid INT AUTO_INCREMENT PRIMARY KEY NOT NULL COMMENT'帖子编号',
	tuid INT NOT NULL COMMENT'发帖用户',
	ttitle VARCHAR(50) NOT NULL COMMENT'帖子标题',
	tinfo VARCHAR(500) NOT NULL COMMENT'发帖内容',
	ttime TIMESTAMP DEFAULT NOW() COMMENT'发帖时间'
)

CREATE TABLE bbsReplys(
	rid INT AUTO_INCREMENT PRIMARY KEY NOT NULL COMMENT'回复号',
	rtid INT NOT NULL COMMENT'主贴id 外键',
	ruid INT NOT NULL COMMENT'回帖用户id 外键',
	rinfo VARCHAR(500) NOT NULL COMMENT'回帖内容',
	rtime TIMESTAMP DEFAULT NOW() COMMENT'回帖时间'
)

ALTER TABLE bbsTopics
ADD CONSTRAINT fk_tuid
FOREIGN KEY(tuid)
REFERENCES bbsUsers(uid)

ALTER TABLE bbsReplys
ADD CONSTRAINT fk_rtid
FOREIGN KEY(rtid)
REFERENCES bbsTopics(tid)

ALTER TABLE bbsReplys
ADD CONSTRAINT fk_uid
FOREIGN KEY(ruid)
REFERENCES bbsUsers(uid)